name: CI y Deploy PHP

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: Validaci√≥n PHP
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v3

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, pdo, pdo_mysql
          coverage: none

      - name: Validar sintaxis PHP
        run: |
          find . -type f -name "*.php" -print0 | xargs -0 -n1 php -l

      - name: Ejecutar PHPUnit (si existe)
        run: |
          if [ -f vendor/bin/phpunit ]; then vendor/bin/phpunit; else echo "No hay pruebas"; fi

  deploy:
    name: Deploy FTP a Hosting
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v3

      - name: Subir archivos por FTP (Hosting ITIU)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          protocol: ftp
          local-dir: ./
          server-dir: /public_html/
          exclude: |
            **/.git*
            **/.github*
            **/node_modules
            **/vendor
            README.md
